"""add moderation reports and actions

Revision ID: 436197347fea
Revises: 21d46f222035
Create Date: 2026-05-14 10:31:57.299653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436197347fea'
down_revision = '21d46f222035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reported_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moderation_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moderation_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_reports_reported_user_id'), ['reported_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_reports_reporter_user_id'), ['reporter_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_reports_reviewed_by'), ['reviewed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_reports_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_reports_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_reports_target_type'), ['target_type'], unique=False)

    op.create_table('moderation_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=180), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['moderation_reports.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moderation_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moderation_actions_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_actions_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_actions_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_actions_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_actions_target_type'), ['target_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_actions_target_user_id'), ['target_user_id'], unique=False)

    op.create_table('user_warnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['moderation_reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_warnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_warnings_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_warnings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_warnings_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_warnings_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_warnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_warnings_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_warnings_report_id'))
        batch_op.drop_index(batch_op.f('ix_user_warnings_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_warnings_admin_user_id'))

    op.drop_table('user_warnings')
    with op.batch_alter_table('moderation_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moderation_actions_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_moderation_actions_target_type'))
        batch_op.drop_index(batch_op.f('ix_moderation_actions_target_id'))
        batch_op.drop_index(batch_op.f('ix_moderation_actions_report_id'))
        batch_op.drop_index(batch_op.f('ix_moderation_actions_created_at'))
        batch_op.drop_index(batch_op.f('ix_moderation_actions_admin_user_id'))
        batch_op.drop_index(batch_op.f('ix_moderation_actions_action_type'))

    op.drop_table('moderation_actions')
    with op.batch_alter_table('moderation_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moderation_reports_target_type'))
        batch_op.drop_index(batch_op.f('ix_moderation_reports_target_id'))
        batch_op.drop_index(batch_op.f('ix_moderation_reports_status'))
        batch_op.drop_index(batch_op.f('ix_moderation_reports_severity'))
        batch_op.drop_index(batch_op.f('ix_moderation_reports_reviewed_by'))
        batch_op.drop_index(batch_op.f('ix_moderation_reports_reporter_user_id'))
        batch_op.drop_index(batch_op.f('ix_moderation_reports_reported_user_id'))
        batch_op.drop_index(batch_op.f('ix_moderation_reports_created_at'))

    op.drop_table('moderation_reports')
    # ### end Alembic commands ###
