"""add community discovery fields

Revision ID: 58285c07626c
Revises: 3a2de4e644bc
Create Date: 2026-04-30 16:00:53.280505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58285c07626c'
down_revision = '3a2de4e644bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university', sa.String(length=180), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('scope', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_column('scope')
        batch_op.drop_column('city')
        batch_op.drop_column('university')

    # ### end Alembic commands ###
