"""add gamification models

Revision ID: 83256e5fe6dd
Revises: c8ef6bb1eca9
Create Date: 2026-05-08 16:52:36.575163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83256e5fe6dd'
down_revision = 'c8ef6bb1eca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('required_points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badges_code'), ['code'], unique=True)

    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badge')
    )
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_badges_badge_id'), ['badge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_badges_user_id'), ['user_id'], unique=False)

    op.create_table('user_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_points_user_id'), ['user_id'], unique=True)

    op.create_table('user_point_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_point_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reference_type', sa.String(length=80), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_point_id'], ['user_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_point_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_point_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_point_transactions_user_point_id'), ['user_point_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_point_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_point_transactions_user_point_id'))
        batch_op.drop_index(batch_op.f('ix_user_point_transactions_user_id'))

    op.drop_table('user_point_transactions')
    with op.batch_alter_table('user_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_points_user_id'))

    op.drop_table('user_points')
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_badges_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_badges_badge_id'))

    op.drop_table('user_badges')
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badges_code'))

    op.drop_table('badges')
    # ### end Alembic commands ###
