"""auto migration

Revision ID: 97949df222bc
Revises: bce9fd8e0736
Create Date: 2026-05-07 16:52:32.362833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97949df222bc'
down_revision = 'bce9fd8e0736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('logo_image', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('target_audience', sa.String(length=180), nullable=True),
    sa.Column('contact_email', sa.String(length=180), nullable=True),
    sa.Column('campaign_url', sa.String(length=255), nullable=True),
    sa.Column('discount_code', sa.String(length=80), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_brands_slug'), ['slug'], unique=True)

    op.create_table('community_sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('sponsorship_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'brand_id', name='uq_community_sponsor_brand')
    )
    with op.batch_alter_table('community_sponsors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_sponsors_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_sponsors_community_id'), ['community_id'], unique=False)

    op.create_table('event_sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('sponsorship_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'brand_id', name='uq_event_sponsor_brand')
    )
    with op.batch_alter_table('event_sponsors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_sponsors_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_sponsors_event_id'), ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_sponsors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_sponsors_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_sponsors_brand_id'))

    op.drop_table('event_sponsors')
    with op.batch_alter_table('community_sponsors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_sponsors_community_id'))
        batch_op.drop_index(batch_op.f('ix_community_sponsors_brand_id'))

    op.drop_table('community_sponsors')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_slug'))
        batch_op.drop_index(batch_op.f('ix_brands_name'))

    op.drop_table('brands')
    # ### end Alembic commands ###
