"""add social room models

Revision ID: bf1c42e5c0ac
Revises: e77c3a3d0767
Create Date: 2026-05-10 20:12:14.812128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1c42e5c0ac'
down_revision = 'e77c3a3d0767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('room_type', sa.String(length=60), nullable=False),
    sa.Column('visibility', sa.String(length=40), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('current_participants', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('meeting_provider', sa.String(length=60), nullable=True),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=80), nullable=True),
    sa.Column('game_title', sa.String(length=120), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_rooms_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_rooms_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_rooms_event_id'), ['event_id'], unique=False)

    op.create_table('social_room_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['social_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_social_room_participant_user')
    )
    with op.batch_alter_table('social_room_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_room_participants_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_room_participants_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_room_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_room_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_social_room_participants_room_id'))

    op.drop_table('social_room_participants')
    with op.batch_alter_table('social_rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_rooms_event_id'))
        batch_op.drop_index(batch_op.f('ix_social_rooms_created_by'))
        batch_op.drop_index(batch_op.f('ix_social_rooms_community_id'))

    op.drop_table('social_rooms')
    # ### end Alembic commands ###
