"""add social feed models

Revision ID: c8ef6bb1eca9
Revises: 97949df222bc
Create Date: 2026-05-08 15:59:46.563508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ef6bb1eca9'
down_revision = '97949df222bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('post_type', sa.String(length=40), nullable=False),
    sa.Column('visibility', sa.String(length=40), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('link_url', sa.String(length=255), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feed_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_posts_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_posts_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_posts_user_id'), ['user_id'], unique=False)

    op.create_table('feed_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['feed_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feed_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_comments_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_comments_user_id'), ['user_id'], unique=False)

    op.create_table('feed_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['feed_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_feed_like_user')
    )
    with op.batch_alter_table('feed_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_likes_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_likes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_feed_likes_post_id'))

    op.drop_table('feed_likes')
    with op.batch_alter_table('feed_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_feed_comments_post_id'))

    op.drop_table('feed_comments')
    with op.batch_alter_table('feed_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_feed_posts_event_id'))
        batch_op.drop_index(batch_op.f('ix_feed_posts_community_id'))

    op.drop_table('feed_posts')
    # ### end Alembic commands ###
