"""add certificate models

Revision ID: e77c3a3d0767
Revises: 83256e5fe6dd
Create Date: 2026-05-08 19:52:20.261494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77c3a3d0767'
down_revision = '83256e5fe6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=20), nullable=False),
    sa.Column('required_points', sa.Integer(), nullable=False),
    sa.Column('required_badge_code', sa.String(length=100), nullable=True),
    sa.Column('issuer_name', sa.String(length=160), nullable=False),
    sa.Column('certificate_type', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_code'), ['code'], unique=True)

    op.create_table('user_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('certificate_number', sa.String(length=120), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'certificate_id', name='uq_user_certificate')
    )
    with op.batch_alter_table('user_certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_certificates_certificate_id'), ['certificate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_certificates_certificate_number'), ['certificate_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_certificates_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_certificates_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_certificates_certificate_number'))
        batch_op.drop_index(batch_op.f('ix_user_certificates_certificate_id'))

    op.drop_table('user_certificates')
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_code'))

    op.drop_table('certificates')
    # ### end Alembic commands ###
